### ISSUE TITLE
Minor Issue about the App `width`

### ISSUE THREAD

**Issue by jayco01** [Deuzi/password-generator#1]
The app gets **really wide on large desktop screens**. Consider setting a `max-width` on the main container to limit how far it stretches. That would improve readability and help keep things looking balanced across screen sizes.

```css
#generator-container {
  max-width: 500px; /* or whatever value fits your design */
  margin: auto;
}
```
